### ISSUE TITLE
Console.Error.WriteLine problem with Swift

### ISSUE THREAD

**Issue by mittelmark** [fusionlanguage/fut#241]
Hi,

Not sure if you saw this:

```cs
public static class Test2 {
        public static void Main (string[] args) {
                string hw = "Hello World!";
                Console.Error.WriteLine($"{hw}");
        }
}
```

works on C, C++, C#, D, Java, JavaScript, Python, Typescript, but not on Swift:

```
8 |    {
 9 |            let hw: String = "Hello World!"
10 |            fputs("\(hw)\n", stderr)
   |                    `- error: reference to var 'stderr' is not concurrency-safe because it involves shared mutable state
11 |    }
```

the code https://github.com/fusionlanguage/fut/blob/master/test/ConsoleErrorWriteLine.fu mentioned only CL although on top Swift is marked with a cross.

Not very important for now, we can just write to normal console in Swift in case of errors,

**Comment by pfusik** [comment]
It seems your are using Swift 6. The tests are run against the (default for the Swift compiler) Swift 5.
I'm aware that Swift 6 have another problem: rejects constant arrays emitted by fut (with an error similar to the above). I don't have a solution for that - any help is welcome. Also for this `stderr` issue.

**Comment by mittelmark** [comment]
Yes, using Swift 6.2.3 on Debian Linux. Using duck.ai and Chat GPT5.3 nano it suggests creating a Stderr struct like this:

```swift
import Foundation

public struct Stderr: TextOutputStream {
    public func write(_ string: String) {
        // This uses Swift I/O abstractions, avoiding direct `stderr` access.
        FileHandle.standardError.write(string.data(using: .utf8)!)
    }
}

public enum Logger {
    public static func log(_ s: String) {
        let out = Stderr()
        out.write(s + "\n")
    }
}

public class Test2 {
    public static func main(_ args: [String]) {
        Logger.log("Hello World!")
    }
}
Test2.main(Array(CommandLine.arguments[1...]))
```

Which seems to compile and run correctly with Swift 6. Not sure if it makes sense to add such a custom (Error) Logger class.

**Comment by pfusik** [comment]
I'm using Swift 6.3.2 (are you sure you have 6.2.3?). It accepts Swift 5 source code by default where `stderr` is okay.

I recently [switched from FileHandle.standardError to stderr](https://github.com/fusionlanguage/fut/commit/16740bc4049cfdb5163dd60865ce3bd15d32c86d) because that's simpler, shorter code. I can easily switch back if this makes Swift 6 happy. Thanks!

**Comment by mittelmark** [comment]
swift --version

Swift version 6.2.3 (swift-6.2.3-RELEASE)

Target: x86_64-unknown-linux-gnu

Probably I should use latest swift before we fix something ... Will download newer version 6.3.2.

**Comment by pfusik** [comment]
I was just making sure it's not a typo.

I don't reproduce the issue on Windows or macOS:

```
C:\0\ci>cat 241.fu
public static class Test2 {
        public static void Main (string[] args) {
                string hw = "Hello World!";
                Console.Error.WriteLine($"{hw}");
        }
}

C:\0\ci>fut -o 241.swift 241.fu

C:\0\ci>swiftc -o 241.exe -swift-version 6 241.swift
   Creating library 241.lib and object 241.exp

C:\0\ci>swiftc --version
Swift version 6.3.2 (swift-6.3.2-RELEASE)
Target: x86_64-unknown-windows-msvc
Build config: +assertions
```
```
fox@wiesmac ~ % swiftc -swift-version 6 241.swift
fox@wiesmac ~ % ./241
Hello World!
fox@wiesmac ~ % swiftc --version
swift-driver version: 1.148.6 Apple Swift version 6.3.2 (swiftlang-6.3.2.1.108 clang-2100.1.1.101)
Target: arm64-apple-macosx26.0
```

**Comment by mittelmark** [comment]
Hmm still the same error, even after updating to 6.3.2.

```
$ cat Test2.fu

public static class Test2 {
        public static void Main (string[] args) {
                string hw = "Hello World!";
                Console.Error.WriteLine($"{hw}");
        }
}
$ fut Test2.fu -o swiftm/Sources/swift/swift.swift
$ cd swiftm
$ swift build 
Building for debugging...
/home/dgroth/workspace/snha4any/fusion/test/swiftm/Sources/swift/swift.swift:10:20: error: reference to var 'stderr' is not concurrency-safe because it involves shared mutable state
 8 |    {
 9 |            let hw: String = "Hello World!"
10 |            fputs("\(hw)\n", stderr)
   |                    `- error: reference to var 'stderr' is not concurrency-safe because it involves shared mutable state
11 |    }
12 | }

/usr/include/stdio.h:151:14: note: var declared here
149 | extern FILE *stdin;               /* Standard input stream.  */
150 | extern FILE *stdout;              /* Standard output stream.  */
151 | extern FILE *stderr;              /* Standard error output stream.  */
    |              `- note: var declared here
152 | /* C89/C99 say they're macros.  Make them happy.  */
153 | #define stdin stdin

$ swift --version
Swift version 6.3.2 (swift-6.3.2-RELEASE)
Target: x86_64-unknown-linux-gnu
```

**Comment by pfusik** [comment]
I reproduce this on Ubuntu 22.04, so it's a Linux-only issue. And only with `-swift-version 6`.
`FileHandle.standardError` is fine.
